# Generated by Django 5.2.17 on 2026-09-29 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0002_testcase"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        db_index=True,
                        default="IN_PROGRESS",
                        max_length=30,
                    ),
                ),
                ("difficulty", models.CharField(default="Easy", max_length=20)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("PROBLEM_INTRO", "Problem Introduction"),
                            ("APPROACH", "Approach & Data Structures"),
                            ("COMPLEXITY", "Complexity Analysis"),
                            ("EDGE_CASES", "Edge Cases"),
                            ("OPTIMIZATION", "Optimization & Trade-offs"),
                            ("CODING", "Coding Implementation"),
                            ("FINAL_EVALUATION", "Final Evaluation"),
                        ],
                        db_index=True,
                        default="PROBLEM_INTRO",
                        max_length=50,
                    ),
                ),
                ("final_feedback", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to="problems.problem",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_sessions",
                        to="submissions.submission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AI_INTERVIEWER", "AI Interviewer"),
                            ("STUDENT", "Student"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("stage", models.CharField(default="PROBLEM_INTRO", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "interview_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_understanding", models.JSONField(default=dict)),
                ("approach_quality", models.JSONField(default=dict)),
                ("technical_reasoning", models.JSONField(default=dict)),
                ("complexity_analysis", models.JSONField(default=dict)),
                ("edge_case_awareness", models.JSONField(default=dict)),
                ("optimization", models.JSONField(default=dict)),
                ("communication", models.JSONField(default=dict)),
                ("coding_correctness", models.JSONField(default=dict)),
                (
                    "overall_score",
                    models.IntegerField(
                        default=85, help_text="Rubric score out of 100"
                    ),
                ),
                ("strengths", models.JSONField(default=list)),
                ("areas_for_improvement", models.JSONField(default=list)),
                ("final_feedback", models.TextField(blank=True, default="")),
                ("recommended_topics", models.JSONField(default=list)),
                ("recommended_problems", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
        ),
    ]
