# Generated by Django 5.2.17 on 2026-09-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProblemProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNSOLVED", "Unsolved"),
                            ("ATTEMPTED", "Attempted"),
                            ("SOLVED", "Solved"),
                        ],
                        default="UNSOLVED",
                        max_length=50,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent", models.IntegerField(default=0)),
                ("hints_used", models.IntegerField(default=0)),
                ("hint_level", models.IntegerField(default=0)),
                ("challenge_score", models.FloatField(blank=True, null=True)),
                ("interview_score", models.FloatField(blank=True, null=True)),
                ("submission_history", models.JSONField(default=list)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
