# Generated by Django 5.2.17 on 2026-09-29 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0002_testcase"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachingInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("student_code", models.TextField(blank=True, default="")),
                ("hint_level", models.IntegerField(blank=True, null=True)),
                ("user_question", models.TextField(blank=True, null=True)),
                ("ai_response", models.TextField()),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("hint", "Hint"),
                            ("challenge", "Challenge"),
                            ("alternative", "Alternative Approach"),
                            ("feedback", "AI Feedback"),
                        ],
                        db_index=True,
                        default="hint",
                        max_length=50,
                    ),
                ),
                (
                    "evaluation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Evaluation metadata (relevance, correctness, hint_specificity, solution_leakage, helpfulness)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_interactions",
                        to="problems.problem",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coaching_interactions",
                        to="submissions.submission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
