# Generated by Django 5.2.17 on 2026-10-09 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaching", "0001_initial"),
        ("problems", "0002_testcase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachinginteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("chat", "Conversational Chat"),
                    ("hint", "Hint"),
                    ("challenge", "Challenge"),
                    ("alternative", "Alternative Approach"),
                    ("feedback", "AI Feedback"),
                ],
                db_index=True,
                default="hint",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CoachingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("UNDERSTANDING_PROBLEM", "Understanding Problem"),
                            ("APPROACH_DISCOVERY", "Approach Discovery"),
                            ("GUIDED_IMPLEMENTATION", "Guided Implementation"),
                            ("DEBUGGING", "Debugging"),
                            ("CORRECTNESS_VERIFICATION", "Correctness Verification"),
                            ("COMPLEXITY_ANALYSIS", "Complexity Analysis"),
                            ("OPTIMIZATION_DISCOVERY", "Optimization Discovery"),
                            ("OPTIMIZED_IMPLEMENTATION", "Optimized Implementation"),
                            ("APPROACH_COMPARISON", "Approach Comparison"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="APPROACH_DISCOVERY",
                        max_length=50,
                    ),
                ),
                (
                    "current_approach",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Current approach details: name, type, is_valid, is_optimal, complexity, description",
                    ),
                ),
                (
                    "explored_approaches",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of previously or currently explored approaches with status and complexity",
                    ),
                ),
                (
                    "solution_status",
                    models.CharField(
                        db_index=True, default="IN_PROGRESS", max_length=50
                    ),
                ),
                (
                    "complexity_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Time and space complexity discussion and validated values",
                    ),
                ),
                (
                    "hints_provided",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of previous clues/hints given to avoid repetition",
                    ),
                ),
                (
                    "misconceptions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Misconceptions identified during session",
                    ),
                ),
                ("last_student_code", models.TextField(blank=True, default="")),
                ("last_execution_result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_sessions",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "problem")},
            },
        ),
        migrations.AddField(
            model_name="coachinginteraction",
            name="coaching_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="coaching.coachingsession",
            ),
        ),
    ]
