# Generated by Django 5.2.17 on 2026-09-28 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0002_testcase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("language", models.CharField(default="python", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("WRONG_ANSWER", "Wrong Answer"),
                            ("RUNTIME_ERROR", "Runtime Error"),
                            ("SYNTAX_ERROR", "Syntax Error"),
                            ("TIME_LIMIT_EXCEEDED", "Time Limit Exceeded"),
                            ("INTERNAL_ERROR", "Internal Error"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "runtime",
                    models.FloatField(default=0.0, help_text="Runtime in milliseconds"),
                ),
                (
                    "memory",
                    models.FloatField(default=0.0, help_text="Memory usage in MB"),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("test_cases_passed", models.IntegerField(default=0)),
                ("total_test_cases", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
